basePath: /
definitions:
  entities.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  entities.Stock:
    properties:
      autor:
        type: string
      ibsn:
        type: string
      id:
        description: Id é um indentificador do estoque
        type: integer
      loja:
        type: string
      nome:
        type: string
      preco:
        type: string
      quantidade:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    name: API Support
  description: this is an inventory control microservice from a bookstores
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Book stock API
  version: "1.0"
paths:
  /estoque/delete/{id}:
    delete:
      consumes:
      - application/json
      description: get string all book in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Stock'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Show a Book in database
  /estoque/insert:
    post:
      consumes:
      - application/json
      description: get string all book in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Stock'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Show a Book in database
  /estoque:
    get:
      consumes:
      - application/json
      description: get string all book in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Stock'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Show a Book in database
  /estoque/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      operationId: get-string-by-int
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Stock'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Show a Book in database
  /estoque/update:
    put:
      consumes:
      - application/json
      description: get string all book in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Stock'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Show a Book in database
swagger: "2.0"
