---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 81dc20b1c7bc502a91146e93ba254e7d5c4c52af
    app.quarkus.io/build-timestamp: 2021-10-29 - 14:43:03 +0000
  labels:
    app.kubernetes.io/name: client
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: client
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8083
  selector:
    app.kubernetes.io/name: client
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 81dc20b1c7bc502a91146e93ba254e7d5c4c52af
    app.quarkus.io/build-timestamp: 2021-10-29 - 14:43:03 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: client
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 81dc20b1c7bc502a91146e93ba254e7d5c4c52af
        app.quarkus.io/build-timestamp: 2021-10-29 - 14:43:03 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: client
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: root/client:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: client
          ports:
            - containerPort: 8083
              name: http
              protocol: TCP
